proxy:
  port: 8080
  authentication: simple
  admin-groups: admins
  users:
  - name: jack
    password: password
    groups: admins
  - name: jeff
    password: password
  docker:
      internal-networking: true
  specs:
  - id: 07_widgets
    display-name: Widgets Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyapps::run_07_widgets()"]
    container-image: shinyapps-img
    container-network: sp-example-net
  - id: 04_mpg
    display-name: MPG Application
    container-cmd: ["R", "-e", "shinyapps::run_04_mpg()"]
    container-image: shinyapps-img
    container-network: sp-example-net
  - id: euler
    display-name: Euler's number
    container-cmd: ["R", "-e", "shiny::runApp('/root/euler')"]
    container-image: euler-img
    container-network: sp-example-net

logging:
  file:
    shinyproxy.log
